




.build/mega2560/src/domotiktamere.cpp : src/domotiktamere.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/domotiktamere.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/domotiktamere.cpp
	@true

